### ISSUE TITLE
Make width and hight properties updatable for Rect and RoundRect?

### ISSUE THREAD

**Issue by AdinAck** [adafruit/Adafruit_CircuitPython_Display_Shapes#16]
I was wondering if it would be possible to make the width and height properties act just like the x and y properties, being that they can be changed later and thus update the shape accordingly.

I would make a pull request for this but I was unable to figure out how to add this functionality, unfortunately.

Thanks!

**Comment by tannewt** [comment]
One gotcha could be that I believe these are implemented with Bitmaps and resizing the Bitmap would cause a re-allocation.

**Comment by jposada202020** [comment]
@empirical-dan and @kmatch98 what do you think about this, could we do the same trick or we would need to change a lot of things, is there an easy solution?

**Comment by kmatch98** [comment]
For this display_shapes library this creates a bitmap for the graphic.  So if it is resized then it should reallocate the whole bitmap again. So “resizing” can do the same thing as just by creating a whole new Rect or RoundRect. 

Seems like that capability is already available so not sure if we want to add this into Rect and RoundRect. And if the user has to fully recreate the shape maybe the user will be more aware to watch out for memory allocation issues(?). 

But if y’all think it makes a lot of of help to add it, it probably will require breaking out part of the `init` code into a separate function so that the resizing setters can recreate the shape.

**Comment by empirical-dan** [comment]
I'm inexperienced but would tend to agree with kmatch. It would possibly
seem cleaner/safer for the user to create a new rectangle rather than
resizing an existing one. Because the layer (group) is essentially a list
they can delete the old rectangle and insert the new one in the same place
if they need to preserve the order.

**Comment by jposada202020** [comment]
I would  prefer not to break `anything` and leave the old code working for everybody, as they are used to. @AdinAck the features are there is just that folks interested in resize the `rectangle` will need to do more code. Personal opinion, lets move-on and see if this is required later on.

**Comment by AdinAck** [comment]
It has been almost a year since I made this issue, so I really don't remember what is going on. Do whatever you want to do!
