### ISSUE TITLE
Circle co-ordinate problems

### ISSUE THREAD

**Issue by empirical-dan** [adafruit/Adafruit_CircuitPython_Display_Shapes#34]
Hi
When drawing a Circle, the x & y properties of the Circle object instance are mis-calculated to being x-r & y-r.

>>> circle = Circle(50, 100, 3, fill=0x0000FF, outline = 0, stroke = 1)
>>> snake_seg.append(circle)
>>> circle2 = snake_seg[len(snake_seg) - 1]
>>> circle2.x
47
>>> circle2.y
97
>>> snake_seg
<Group>
>>>

**Comment by kmatch98** [comment]
The x and y location for objects in displayio refers to the position of the object’s upper left corner. So the leftmost extent of this circle is at `x=(50-3)` and the upper most position is at `y=(100-3)`.

Agreed that it’s a bit confusing though but it’s the standard that was selected since a lot of display related things are rectangular. However if you want it to use a different x,y to refer to the center point you could write a subClass “wrapper” based on displayio.Group that offsets the position like you prefer.

Thanks for bringing up this issue!  I suspect others will encounter a similar question and maybe this will help.

**Comment by empirical-dan** [comment]
Thanks kmatch
I understand that it's the top left corner. What I'm saying is that the top left corner obtained via the group object from displayio gives a co-ordinate that is offset by the radius. This only happens for Circle. Roundrect gives the expected results as per below. Could this be a problem with the TFT_Gizmo library as the Circle shape is actually drawn using a Roundrect so it's probably not that? I've changed to using Roundrect to draw circles so not a big issue for me but I thought others may run into the same problem.

display = tft_gizmo.TFT_Gizmo()

# Create a Group
snake_segs = displayio.Group()

# Add the Group to the Display
display.show(snake_segs)
>>> roundrect = RoundRect(x, y, 6, 6, 1, fill=0x0000FF)
>>> 
>>> roundrect = RoundRect(50, 100, 6, 6, 1, fill=0x0000FF)
>>> snake_segs.append(roundrect)
>>> snake_segs[len(snake_segs) - 1].x
50
>>> snake_segs[len(snake_segs) - 1].y
100
>>> snake_segs
<Group>

**Comment by empirical-dan** [comment]
I've had another look at this.
It's a result of Circle being a subclass of RoundRect. Therefore Circle creates a RoundRect with the top left corner being x-r, y-r. However, you define the circle by the centre x,y as per the documentation. This makes no sense. When I instantiate an Object with a certain x & y I don't expect the code to change those values and still call them x & y within the Object.
In my opinion, Circle needs a separate class that doesn't inherit from RoundRect (at least not its co-ordinate system). In some shape libraries there is also the facility to create shapes based on the centre co-ordinate and this would be helpful  for consistency of dealing with shape placement.

**Comment by kmatch98** [comment]
Totally understand what you mean by this one being defined differently than other shapes. I don’t know the history but I can only speculate it was thought that most folks would think about placing the center of a circle (rather than the upper left corner).  At same time I understand how it’s not consistent and can be confusing.  I see the keywords are called x0, y0 in the library but most people probably just use it with positional arguments so would never even know that.

Perhaps a good solution is having input options of defining the position by either x,y (as upper left corner) or by x_center, y_center (center of the circle).  It might make sense for a revised function to require all keyword arguments.  And that would force someone to be explicit in defining how they want to use it. Interested to hear your thoughts. 

Are you interested in taking this one on?

**Comment by empirical-dan** [comment]
Hi
I'm just learning a bit of Python to encourage my 10yo son so this may not be the best way to go about it but I've just added the last two lines to the library source file as per below: (i.e. self.x0 = x0, self.y0 = y0). This appears to be consistent with the comments in the existing source code so that when you define a circle (using the centre co-ordinates x0, y0) the Circle object gains these attributes via the __init__ method. There are lots of parent classes but from what I can gather, CircuitPython uses attributes for co-ordinates in displayio rather than properties so my simple solution may suffice? The circle module works how I would want it to. Are you able to submit this for me to the author/maintainer? 
Best
Dan




# SPDX-FileCopyrightText: 2019 Limor Fried for Adafruit Industries
#
# SPDX-License-Identifier: MIT

"""
`circle`
================================================================================

Various common shapes for use with displayio - Circle shape!


* Author(s): Limor Fried

Implementation Notes
--------------------

**Software and Dependencies:**

* Adafruit CircuitPython firmware for the supported boards:
  https://github.com/adafruit/circuitpython/releases

"""

from adafruit_display_shapes.roundrect import RoundRect

__version__ = "0.0.0-auto.0"
__repo__ = "https://github.com/adafruit/Adafruit_CircuitPython_Display_Shapes.git"


class Circle(RoundRect):
    # pylint: disable=too-few-public-methods, invalid-name
    """A circle.

    :param x0: The x-position of the center.
    :param y0: The y-position of the center.
    :param r: The radius of the circle.
    :param fill: The color to fill the circle. Can be a hex value for a color or
                 ``None`` for transparent.
    :param outline: The outline of the circle. Can be a hex value for a color or
                 ``None`` for no outline.
    :param stroke: Used for the outline. Will not change the radius.

    """

    def __init__(self, x0, y0, r, *, fill=None, outline=None, stroke=1):
        super().__init__(
            x0 - r,
            y0 - r,
            2 * r + 1,
            2 * r + 1,
            r,
            fill=fill,
            outline=outline,
            stroke=stroke,
        )
        self.x0 = x0 # added by empirical-dan
        self.y0 = y0 # added by empirical-dan

**Comment by empirical-dan** [comment]
I've made a commit and a pull request. I hope this is OK, it's my first time...

**Comment by jposada202020** [comment]
@empirical-dan Changes you merge in the PR were merge, Do you think we could close this issue?. thanks :)
